# ? Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ? Connexion à la base H2 en mémoire
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ? Hibernate : génération automatique du schéma
spring.jpa.hibernate.ddl-auto=update

# ? Log des requêtes SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.main.web-application-type=reactive